version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fixtrack-backend
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL=jdbc:postgresql://db.ujlfxihvzcmjqjbhaacu.supabase.co:5432/postgres
      DATABASE_USERNAME=postgres
      DATABASE_PASSWORD=Deepderin0.?

      CLOUDINARY_CLOUD_NAME=djixp5o9n
      CLOUDINARY_API_KEY=852652644424516
      CLOUDINARY_API_SECRET=Wc1yEYdFeUGMJWUZJ6WTyQU6s3o

    depends_on: [] # Harici PostgreSQL kullandığınız için boş belirtiliyor